import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { Prisma, RoleName } from '@prisma/client';
import { LeasesRepository } from './leases.repository';
import { LeasesMapper } from './leases.mapper';
import {
  CreateLeaseDto,
  UpdateLeaseDto,
  TerminateLeaseDto,
  RenewLeaseDto,
  AddAmendmentDto,
  QueryLeaseDto,
} from './dto';
import { PaginatedResponseDto } from '../../common/dto';
import { PrismaService } from '../../prisma/prisma.service';
import { AuthenticatedUser } from '../../common/interfaces';
import { addDays } from '../../common/utils/date-helpers.util';
import { generatePdfStub } from '../../common/utils/pdf-generator.util';
import { NotificationsService } from '../notifications/notifications.service';

@Injectable()
export class LeasesService {
  constructor(
    private readonly repo: LeasesRepository,
    private readonly prisma: PrismaService,
    private readonly notifications: NotificationsService,
  ) {}

  async findAll(organizationId: string, query: QueryLeaseDto) {
    const where: Prisma.LeaseWhereInput = { organizationId, deletedAt: null };
    if (query.status) where.status = query.status;
    if (query.propertyId) where.propertyId = query.propertyId;
    if (query.tenantId) where.tenantId = query.tenantId;

    const [items, total] = await Promise.all([
      this.repo.findMany(where, (query.page - 1) * query.limit, query.limit, {
        [query.sortBy ?? 'createdAt']: query.sortOrder ?? 'desc',
      }),
      this.repo.count(where),
    ]);

    return new PaginatedResponseDto(items.map(LeasesMapper.toResponse), total, query.page, query.limit);
  }

  async findOne(id: string, user: AuthenticatedUser) {
    const lease = await this.getOwnedOrThrow(id, user);
    return LeasesMapper.toResponse(lease);
  }

  async create(organizationId: string, dto: CreateLeaseDto) {
    const property = await this.prisma.property.findFirst({
      where: { id: dto.propertyId, organizationId, deletedAt: null },
    });
    if (!property) throw new BadRequestException('Bien invalide pour cette organisation.');
    if (property.status !== 'DISPONIBLE') throw new ConflictException("Ce bien n'est pas disponible à la location.");

    const tenant = await this.prisma.tenant.findFirst({ where: { id: dto.tenantId, organizationId, deletedAt: null } });
    if (!tenant) throw new BadRequestException('Locataire invalide pour cette organisation.');

    const startDate = new Date(dto.startDate);

    const lease = await this.prisma.$transaction(async (tx) => {
      const created = await tx.lease.create({
        data: {
          organization: { connect: { id: organizationId } },
          property: { connect: { id: dto.propertyId } },
          ownerId: property.ownerId,
          tenant: { connect: { id: dto.tenantId } },
          startDate,
          endDate: dto.endDate ? new Date(dto.endDate) : null,
          rentAmount: dto.rentAmount,
          depositAmount: dto.depositAmount,
          paymentFrequency: dto.paymentFrequency,
          indexationRate: dto.indexationRate,
          status: 'ACTIF',
        },
      });

      await tx.property.update({ where: { id: dto.propertyId }, data: { status: 'OCCUPE' } });

      await tx.leaseDocument.create({
        data: { leaseId: created.id, type: 'CONTRAT_PDF', url: `/generated/leases/${created.id}/contract.json` },
      });

      // First rent installment due at lease start; subsequent ones are generated by the
      // monthly cron job (generateMonthlyPaymentsJob, see notifications.scheduler.ts).
      await tx.payment.create({
        data: {
          organization: { connect: { id: organizationId } },
          lease: { connect: { id: created.id } },
          amountDue: dto.rentAmount,
          dueDate: startDate,
          status: 'EN_ATTENTE',
        },
      });

      return created;
    });

    const full = await this.repo.findById(lease.id);
    return LeasesMapper.toResponse(full!);
  }

  async update(id: string, dto: UpdateLeaseDto) {
    await this.ensureExists(id);
    const lease = await this.repo.update(id, {
      ...dto,
      endDate: dto.endDate !== undefined ? new Date(dto.endDate) : undefined,
    });
    return LeasesMapper.toResponse(lease);
  }

  async renew(id: string, dto: RenewLeaseDto) {
    const lease = await this.ensureExists(id);
    if (lease.status !== 'ACTIF') throw new ConflictException('Seul un contrat actif peut être renouvelé.');

    const updated = await this.repo.update(id, { endDate: new Date(dto.newEndDate) });
    if (dto.amendmentDescription) {
      await this.repo.addAmendment(id, dto.amendmentDescription, new Date());
    }

    await this.notifications.notify({
      organizationId: lease.organizationId,
      userId: await this.tenantUserId(lease.tenantId),
      type: 'EXPIRATION_CONTRAT',
      title: 'Contrat renouvelé',
      message: `Votre contrat a été renouvelé jusqu'au ${dto.newEndDate}.`,
    });

    return LeasesMapper.toResponse(updated);
  }

  async terminate(id: string, dto: TerminateLeaseDto) {
    const lease = await this.ensureExists(id);
    if (lease.status !== 'ACTIF') throw new ConflictException('Seul un contrat actif peut être résilié.');

    const [updated] = await this.prisma.$transaction([
      this.prisma.lease.update({
        where: { id },
        data: { status: 'RESILIE', endDate: new Date(dto.terminationDate) },
        include: { documents: true, amendments: true, property: true, tenant: true },
      }),
      this.prisma.property.update({ where: { id: lease.propertyId }, data: { status: 'DISPONIBLE' } }),
      this.prisma.payment.updateMany({
        where: { leaseId: id, status: 'EN_ATTENTE', dueDate: { gt: new Date(dto.terminationDate) } },
        data: { status: 'ANNULE' },
      }),
    ]);

    await this.prisma.auditLog.create({
      data: {
        organizationId: lease.organizationId,
        action: 'LEASE_TERMINATED',
        entity: 'Lease',
        entityId: id,
        metadata: { reason: dto.reason ?? null, terminationDate: dto.terminationDate },
      },
    });

    const tenantUserId = await this.tenantUserId(lease.tenantId);
    await this.notifications.notify({
      organizationId: lease.organizationId,
      userId: tenantUserId,
      type: 'EXPIRATION_CONTRAT',
      title: 'Contrat résilié',
      message: `Votre contrat de location a été résilié à compter du ${dto.terminationDate}.`,
    });

    return LeasesMapper.toResponse(updated);
  }

  async addAmendment(id: string, dto: AddAmendmentDto) {
    await this.ensureExists(id);
    await this.repo.addAmendment(id, dto.description, new Date(dto.effectiveDate));
    const updated = await this.repo.findById(id);
    return LeasesMapper.toResponse(updated!);
  }

  async contractPdf(id: string, user: AuthenticatedUser) {
    const lease = await this.getOwnedOrThrow(id, user);
    return generatePdfStub('lease-contract', {
      leaseId: lease.id,
      property: lease.property,
      tenant: lease.tenant,
      startDate: lease.startDate,
      endDate: lease.endDate,
      rentAmount: Number(lease.rentAmount),
      depositAmount: Number(lease.depositAmount),
    });
  }

  async expiringSoon(organizationId: string, days: number) {
    const from = new Date();
    const to = addDays(from, days);
    const leases = await this.repo.expiringSoon(organizationId, from, to);
    return leases.map(LeasesMapper.toResponse);
  }

  private async getOwnedOrThrow(id: string, user: AuthenticatedUser) {
    const lease = await this.repo.findById(id);
    if (!lease) throw new NotFoundException('Contrat introuvable.');

    if (user.roleName === RoleName.LOCATAIRE) {
      const tenant = await this.prisma.tenant.findUnique({ where: { id: lease.tenantId } });
      if (!tenant || tenant.userId !== user.id) {
        throw new ForbiddenException("Vous n'avez pas accès à ce contrat.");
      }
    }

    return lease;
  }

  private async tenantUserId(tenantId: string): Promise<string | undefined> {
    const tenant = await this.prisma.tenant.findUnique({ where: { id: tenantId } });
    return tenant?.userId ?? undefined;
  }

  private async ensureExists(id: string) {
    const lease = await this.repo.findById(id);
    if (!lease) throw new NotFoundException('Contrat introuvable.');
    return lease;
  }
}
